[package]
name = "system76-power"
version = "1.0.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]

[dependencies]
dbus = "=0.6.2"
libc = "0.2"
clap = "2.32.0"
log = "0.4.3"
fern = "0.5.6"
sysfs-class = "0.1"

[build-dependencies]
vergen = "0.1.1"
